In [1]:
from tensorflow.keras import models, layers
import numpy as np

In [2]:
data_set = np.loadtxt('data/ThoraricSurgery3.csv', delimiter=',')
data_set

array([[ 1.  ,  2.88,  2.16, ...,  0.  , 60.  ,  0.  ],
       [ 2.  ,  3.4 ,  1.88, ...,  0.  , 51.  ,  0.  ],
       [ 2.  ,  2.76,  2.08, ...,  0.  , 59.  ,  0.  ],
       ...,
       [ 2.  ,  3.04,  2.08, ...,  0.  , 52.  ,  0.  ],
       [ 2.  ,  1.96,  1.68, ...,  0.  , 79.  ,  0.  ],
       [ 2.  ,  4.72,  3.56, ...,  0.  , 51.  ,  0.  ]])

In [3]:
X = data_set[:, :16]
y = data_set[:, 16]

In [4]:
X[:3]

array([[ 1.  ,  2.88,  2.16,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,
         3.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 60.  ],
       [ 2.  ,  3.4 ,  1.88,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 51.  ],
       [ 2.  ,  2.76,  2.08,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 59.  ]])

In [5]:
y[:3]

array([0., 0., 0.])

In [7]:
model = models.Sequential()
model.add(layers.Dense(30, input_dim=16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [10]:
# 1. sequential(), 2. sub-classing

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 30)                510       
                                                                 
 dense_3 (Dense)             (None, 1)                 31        
                                                                 
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
h = model.fit(X, y, epochs=5, batch_size=16)

Epoch 1/5
30/30 [==============================] - 1s 1ms/step - loss: 0.4634 - accuracy: 0.8404
Epoch 2/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4571 - accuracy: 0.8489
Epoch 3/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4461 - accuracy: 0.8468
Epoch 4/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4342 - accuracy: 0.8468
Epoch 5/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4367 - accuracy: 0.8489
